### ISSUE TITLE
check/ update api doc

### ISSUE THREAD

**Issue by github4touchdouble** [Embloy/Embloy-Core-Server#80]
@github4touchdouble: 
api/v0/registration_controller line 65, substituted original with unauthorized_error (trigger by wrong creds at new user verification)
api/v0/registration_controller line 80 substituted original with unnecessary_error (trigger by already verified user)
@carlobortolan;
doc every new endpoint
check whether current doc is still correct for every endpoint you edited

**Comment by carlobortolan** [comment]
Switched to Postman doc ([postman.com/embloy](https://www.postman.com/embloy)) and updated internal API docs ([custom_exceptions_doc.md](https://github.com/Embloy/Embloy-Core-Server/blob/master/app/service/custom_exceptions_doc.md) and [authentication_token_service_doc.md](https://github.com/Embloy/Embloy-Core-Server/blob/master/app/service/authentication_token_service_doc.md)) with newest genius query and quicklink changes.
